spring:
  application:
    name: andymall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#  datasource:
server:
  port: 12000
#    driver-class-name: com.mysql.cj.jdbc.Driver