#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.101.104:3306/andymall_sms
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  config:
#    import:
#      - nacos:nacos-config-example.properties?refresh=true
#  application:
#    name: andymall-coupon
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 13000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#
